Add Documentation Examples
pyxem/diffsims pull request #209
Opened 2024-04-17 18:17 UTC by CSSFrancis

#### Description of the change

This depends on #205 and adds Examples to the documentation. 

 
#### Progress of the PR
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Unit tests with pytest for all lines
- [ ] Clean code style by [running black](https://diffsims.readthedocs.io/en/latest/contributing.html#get-the-style-right)

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the
      unreleased section in `CHANGELOG.rst`.
- [ ] Contributor(s) are listed correctly in `credits` in `diffsims/release_info.py` and
      in `.zenodo.json`.

2024-04-21 15:00 UTC, CSSFrancis commented
@hakonanes Any chance you can look over this if you get the chance?  Mostly it just copies the examples in orix/pyxem

2024-04-21 15:56 UTC, hakonanes commented
Yes, I can. But since this depends on #205, I'll do so after that one is reviewed and merged (I have some questions regarding the `intensity` attribute, e.g.).

2024-05-09 15:40 UTC, hakonanes commented
I can review this once you rebase and make any changes you'd like.

2024-05-09 16:00 UTC, CSSFrancis commented
@hakonanes what is your opinion on including the examples for the distribution?

2024-05-09 16:05 UTC, hakonanes commented
I'd include them, as currently they are just small Python files.

2024-05-09 16:59 UTC, CSSFrancis commented
@hakonanes This is good to be reviewed when you have the chance.

2024-05-09 17:13 UTC, hakonanes requested changes

2024-05-09 17:13 UTC, hakonanes commented on doc/index.rst
> +    Examples <examples/index>
I suggest to take the approach we have in orix, with:
* four tiles on the front page linking to tutorials, examples, technical reference, and contributing guide: https://raw.githubusercontent.com/pyxem/orix/develop/doc/index.rst
* tutorials and examples included in the user guide under *Usage*: https://raw.githubusercontent.com/pyxem/orix/develop/doc/user/index.rst
* Just the *User guide* in the top navbar

We don't have a user guide separate from the tutorials and examples (just installation and a few references), so I think this is simpler.

2024-05-09 17:13 UTC, hakonanes commented on examples/creating_a_simulation_library/README.rst
> +.. _examples-index:
Duplicate label?

2024-05-09 17:13 UTC, hakonanes commented on examples/creating_a_simulation_library/README.rst
> +These examples show specific workflows for creating a library of simulations
```suggestion
These examples show specific workflows for creating a library of simulations.
```

2024-05-09 17:13 UTC, hakonanes commented on examples/creating_a_simulation_library/README.rst
> +Simulation Library
I suggest to rename this section to something slightly more descriptive. Perhaps "Creating a simulation library", or something similar?

2024-05-09 17:13 UTC, hakonanes commented on examples/creating_a_simulation_library/migration_guide.py
> +from diffsims.libraries.structure_library import StructureLibrary
I suggest to add a blank line between 3rd party packages and internal imports.

And to import classes from diffpy.structure directly, like

from diffpy.structure import Atom, Lattice, Structure

2024-05-09 17:13 UTC, hakonanes commented on examples/creating_a_simulation_library/migration_guide.py
> +axs[0, 1].set_title("New")
To prevent the display of the returned Matplotlib object in the gallery:

```suggestion
_ = axs[0, 1].set_title("New")
```

2024-05-09 17:13 UTC, hakonanes commented on examples/creating_a_simulation_library/simulating_diffraction_patterns.py
> +Simulating One Diffraction Pattern for a Single Phase
Rename to something like *Simple diffraction pattern simulations*, if that is the intent of the example? Subsections can then be shortened to something like:
* One pattern for one phase
* Multiple patterns for one phase
* Multiple patterns for multiple phases
* Plotting a "Real" Diffraction Pattern

2024-05-09 17:13 UTC, hakonanes commented on examples/creating_a_simulation_library/simulating_diffraction_patterns.py
> +sim.plot(show_labels=True)  # plot the first (and only) diffraction pattern
```suggestion
_ = sim.plot(show_labels=True)  # plot the first (and only) diffraction pattern
```

2024-05-09 17:13 UTC, hakonanes commented on examples/creating_a_simulation_library/simulating_diffraction_patterns.py
> +sim.irot[3].plot(show_labels=True)  # plot the fourth(45 degrees) diffraction pattern
```suggestion
_ = sim.irot[3].plot(show_labels=True)  # plot the fourth(45 degrees) diffraction pattern
```

2024-05-09 17:13 UTC, hakonanes commented on examples/creating_a_simulation_library/simulating_diffraction_patterns.py
> +sim.plot(show_labels=True)  # plot the first diffraction pattern
```suggestion
_ = sim.plot(show_labels=True)  # plot the first diffraction pattern
```

2024-05-09 17:13 UTC, hakonanes commented on examples/creating_a_simulation_library/simulating_diffraction_patterns.py
> +sim.plot(
```suggestion
_ = sim.plot(
```

2024-05-09 17:13 UTC, hakonanes commented on examples/creating_a_simulation_library/simulating_diffraction_patterns.py
> +sim.iphase["al_2"].irot[3].plot(
```suggestion
_ = sim.iphase["al_2"].irot[3].plot(
```

2024-05-09 17:13 UTC, hakonanes commented on examples/creating_a_simulation_library/simulating_diffraction_patterns.py
> +plt.imshow(dp)
```suggestion
_ = plt.imshow(dp)
```

2024-05-09 17:13 UTC, hakonanes commented on doc/conf.py
> +# -- Sphinx-Gallery---------------
If we add `autosummary_generate = True` below the sphinx gallery config (doesn't have to be there, but that's cleanest), we should get mini-galleries in the API reference pointing to examples where an object is used. See https://sphinx-gallery.github.io/stable/configuration.html#references-to-examples and e.g. https://pyxem.readthedocs.io/en/stable/reference/generated/pyxem.signals.DiffractionVectors2D.html

2024-05-09 17:13 UTC, hakonanes commented on examples/creating_a_simulation_library/simulating_diffraction_patterns.py
> +=====================================================
This example should have a brief description.

2024-05-12 08:45 UTC, hakonanes commented
@CSSFrancis, if it's fine with you, I'll add the following fixes and updates to your branch:
* Use numpydoc instead of sphinx.ext.napoleon, giving us useful warnings for how to improve our docstrings
* Restructure doc/index.rst perfectly in line with orix (and fixing some links etc.)
* Fix minigalleries in API (since we use custom templates, we have to add it explicitly, which I forgot; sorry!)
* Rename Gallery of Examples -> Examples, and fix heading level (use === above and below)
* Some other smaller things

2024-05-12 11:33 UTC, CSSFrancis commented
> @CSSFrancis, if it's fine with you, I'll add the following fixes and updates to your branch:
> 
> * Use numpydoc instead of sphinx.ext.napoleon, giving us useful warnings for how to improve our docstrings
> * Restructure doc/index.rst perfectly in line with orix (and fixing some links etc.)
> * Fix minigalleries in API (since we use custom templates, we have to add it explicitly, which I forgot; sorry!)
> * Rename Gallery of Examples -> Examples, and fix heading level (use === above and below)
> * Some other smaller thing

@hakonanes Go for it!  I'm pretty much always okay with you adding things to my PR's :).

2024-05-13 20:27 UTC, hakonanes commented
Thanks, I've done so now. I'll go over the docs built in this PR tomorrow, and then we can merge and release.

2024-05-13 20:33 UTC, hakonanes approved these changes

2024-05-13 20:33 UTC, merged